---
- name: Configure OS
  hosts: all
  become: yes
  roles:
    - hostname
    - firewall
    - etc-hosts
    - register

- name: Install and Configure IdM
  hosts: all
  become: yes
  roles:
    - install-idm
